apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-app
  template:
    metadata:
      labels:
        app: transaction-app
    spec:
      containers:
      - name: transaction-app
        image: nileshrathi99/transaction-app:1.1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: transaction-config-prod
        - secretRef:
            name: transaction-secret-prod

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
